---
- name: Configure sysctl files
  ansible.builtin.include_tasks:
    file: "add-sysctl.yml"
  loop: "{{ sysctl_files }}"
  loop_control:
    label: "{{ item.name }}"

- name: Configure kernel modules to load
  ansible.builtin.template:
    src: "modprobe/modules-load.conf"
    dest: "{{ modprobe_modules_load_file }}"
    mode: "u=rw,g=r,o=r"
  when: "modprobe_modules | selectattr('state', 'equalto', 'loaded') | list | length >= 1"
  notify: restart systemd-modules-load

- name: Unload blacklisted kernel modules
  community.general.modprobe:
    name: "{{ item.name }}"
    state: "absent"
  loop: "{{ modprobe_modules | selectattr('state', 'equalto', 'blacklisted') | list }}"
  loop_control:
    label: "{{ item.name }}"

- name: Blacklist kernel modules
  ansible.builtin.template:
    src: "modprobe/modprobe-blacklist.conf"
    dest: "{{ modprobe_blacklist_config_file }}"
    mode: "u=rw,g=r,o=r"
  when:
    - modprobe_modules | selectattr('state', 'equalto', 'blacklisted') | list | length >= 1
  notify:
    - update-initramfs

- name: Configure kernel module options
  ansible.builtin.template:
    src: "modprobe/modprobe-options.conf"
    dest: "{{ modprobe_options_config_file }}"
    mode: "u=rw,g=r,o=r"
  when: >
    modprobe_modules |
      selectattr('state', 'equalto', 'loaded') |
      selectattr('options', 'defined') |
      list | length >= 1
  notify:
    - update-initramfs
    - restart systemd-modules-load
