---

- name: Refresh apt cache
  apt:
    update_cache: yes
  changed_when: false

- name: Install https support for apt
  apt:
    pkg:
      - apt-transport-https
    state: present
  when: not (ansible_distribution == "Debian" and ansible_distribution_version is version('10', '>='))

- name: Install gnupg on newer ubuntu/debian
  apt:
    pkg:
      - gnupg
    state: present
  when: >
    (ansible_distribution == "Debian" and ansible_distribution_version is version('9', '>=')) or
    (ansible_distribution == "Ubuntu" and ansible_distribution_version is version('18.04', '>='))

- name: Install gnupg2 on older ubuntu/debian
  apt:
    pkg:
      - gnupg2
    state: present
  when: >
    (ansible_distribution == "Debian" and ansible_distribution_version is version('9', '<')) or
    (ansible_distribution == "Ubuntu" and ansible_distribution_version is version('18.04', '<'))

- name: Configure apt mirror
  template:
    src: "templates/sources.list.{{ ansible_distribution|lower }}"
    dest: /etc/apt/sources.list
  when: ansible_os_family == "Debian"
  register: apt_mirror

- name: Refresh apt cache when mirror changes
  apt:
    update_cache: yes
  when: apt_mirror.changed == true

- name: Install needrestart
  apt:
    pkg: needrestart
    state: present

- name: Install intel microcode on physical hosts
  apt:
    pkg: "intel-microcode"
  when:
    - "ansible_virtualization_role == 'host'"
    - "ansible_processor | lower is search('intel')"

- name: Install amd64 microcode on physical hosts
  apt:
    pkg: "amd64-microcode"
  when:
    - "ansible_virtualization_role == 'host'"
    - "ansible_processor | lower is search('amd')"

- name: Add keys for useful repos
  apt_key:
    url: "{{ item.key.url }}"
    id: "{{ item.key.id | default(omit) }}"
    state: present
  with_items: "{{ useful_repos }}"

- name: Add useful repos
  apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.name }}"
    update_cache: yes
    state: present
  with_items: "{{ useful_repos }}"

- name: Install useful packages
  apt:
    pkg: "{{ useful_packages }}"
    state: present
