---
- name: "Enable backports repo on debian"
  ansible.builtin.template:
    src: "apt/sources.list.debian-backports"
    dest: "/etc/apt/sources.list.d/debian-backports.list"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  register: _apt_enable_debian_backports

- name: "Refresh apt cache when mirror changes"  # noqa no-handler
  ansible.builtin.apt:
    update_cache: true
  when: _apt_enable_debian_backports.changed

- name: Install needrestart from backports on debian stretch  # noqa package-latest no-handler
  ansible.builtin.apt:
    pkg: needrestart
    default_release: "{{ ansible_distribution_release }}-backports"
    state: latest
  when:
    - _apt_enable_debian_backports.changed
    - ansible_distribution_release == "stretch"

- name: Install nonfree firmware for some system vendors
  ansible.builtin.apt:
    pkg: "firmware-linux-nonfree"
    install_recommends: false
  when: ansible_system_vendor.lower() is search(item.lower())
  loop: "{{ nonfree_firmware_system_vendors }}"
