---

- name: Enable backports repo on debian
  apt_repository:
    filename: "debian-backports"
    repo: "deb {{ debian_mirror }} {{ debian_backports_components }}"
    update_cache: yes
    state: present

- name: Install needrestart from backports on debian stretch
  apt:
    pkg: needrestart
    default_release: "{{ansible_distribution_release}}-backports"
    state: latest
  when: ansible_distribution_release == "stretch"

- name: Install nonfree firmware on debian machines with dell hardware
  apt:
    pkg: "firmware-linux-nonfree"
    install_recommends: no
  when: ansible_system_vendor | lower is search("dell")

- name: Install nonfree network firmware on debian machines when required
  apt:
    pkg: "{{ item.package }}"
    install_recommends: no
  when: "item.module in loaded_network_kmods"
  loop: "{{ nonfree_network_firmware }}"
