---

- name: Enable reboot on kernel panic
  sysctl:
    key: kernel.panic
    value: '20'
    sysctl_file: /etc/sysctl.d/kernel.panic.conf

- name: Enable kernel panic on oops
  sysctl:
    key: kernel.panic_on_oops
    value: '1'
    sysctl_file: /etc/sysctl.d/kernel.panic_on_oops.conf

- name: Set linux cmdline default options
  lineinfile:
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((?!.*{{ item }}.*).*)"$'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 {{ item }}"'
  with_items: "{{ grub_cmdline }}"
  notify: update-grub
