---
- name: Install cpupower
  ansible.builtin.apt:
    pkg: "linux-cpupower"

- name: Add cpupower defaults file
  ansible.builtin.template:
    src: "cpupower/defaults"
    dest: "/etc/default/cpupower"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
  register: _defaults_file
  notify: restart cpupower

- name: Create /etc/systemd/scripts/
  ansible.builtin.file:
    path: "/etc/systemd/scripts/"
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rx,o=rx"
    state: "directory"

- name: Add cpupower systemd script
  ansible.builtin.template:
    src: "cpupower/cpupower"
    dest: "/etc/systemd/scripts/cpupower"
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rx,o=rx"

- name: Add cpupower systemd service
  ansible.builtin.template:
    src: "cpupower/cpupower.service"
    dest: "/etc/systemd/system/cpupower.service"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
  register: _unit_file

- name: Start and enable cpupower systemd service
  ansible.builtin.systemd:
    name: "cpupower.service"
    daemon_reload: >-
      {{ true if _unit_file is changed or _defaults_file is changed else false }}
    enabled: true
    state: started
