---
- name: Install NIC specific packages when required
  ansible.builtin.apt:
    pkg: "{{ item.package }}"
    install_recommends: false
  when:
    - "item.module in loaded_nic_kmods | json_query('[*].module')"
    - "ansible_distribution | lower in item.distributions"
  loop: "{{ nic_packages }}"
  loop_control:
    label: "{{ item.module }}"
