---
- name: install grub
  ansible.builtin.command:
    cmd: dpkg-reconfigure -f noninteractive grub-pc

- name: install grub-efi
  ansible.builtin.shell:
    cmd: >
      dpkg-reconfigure -f noninteractive grub-efi-$(dpkg --print-architecture)

- name: update-grub
  ansible.builtin.command:
    cmd: update-grub

- name: update-initramfs
  ansible.builtin.command:
    cmd: update-initramfs -u -k all

- name: restart systemd-modules-load
  ansible.builtin.service:
    name: systemd-modules-load
    state: restarted

- name: restart cpupower
  ansible.builtin.service:
    name: cpupower
    state: restarted
