---

- name: update-grub
  command: update-grub

- name: update-initramfs
  command: update-initramfs -u -k all

- name: restart systemd-modules-load
  service:
    name: systemd-modules-load
    state: restarted
