---
- name: update-grub
  ansible.builtin.command:
    cmd: update-grub

- name: update-initramfs
  ansible.builtin.command:
    cmd: update-initramfs -u -k all

- name: restart systemd-modules-load
  ansible.builtin.service:
    name: systemd-modules-load
    state: restarted

- name: restart cpupower
  ansible.builtin.service:
    name: cpupower
    state: restarted
