---
- name: Converge
  hosts: all
  tasks:
    - name: "Include wandansible.common"
      ansible.builtin.include_role:
        name: "wandansible.common"
      vars:
        locale: "C.UTF-8"
        timezone: "Etc/UTC"

        debian_mirror: "https://mirror.fsmg.org.nz/debian/"
        debian_backports_mirror: >-
          {{ "http://archive.debian.org/debian/"
             if ansible_distribution == "Debian"
            and ansible_distribution_major_version is version("10", "<=")
            else debian_mirror }}
        ubuntu_mirror: "https://mirror.fsmg.org.nz/ubuntu/"

        apt_conf_files:
          - name: 90phased-updates
            config: |
              APT::Get::Always-Include-Phased-Updates "1";

        apt_repos:
          - name: tailscale
            repo: >-
              deb [signed-by=/etc/apt/keyrings/tailscale.gpg]
              https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main
            key:
              url: https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}.asc
              id: 2596A99EAAB33821893C0A79458CA832957F5868
              keyring: /etc/apt/keyrings/tailscale.gpg

  environment:
    ANSIBLE_UNSAFE_WRITES: "true"
