---
- name: Converge
  hosts: all
  tasks:
    - name: "Include wandansible.common"
      ansible.builtin.include_role:
        name: "wandansible.common"
      vars:
        locale: "C.UTF-8"
        timezone: "Etc/UTC"

        keyboard_layout: "us"

        debian_mirror_url: >-
          {{ "http://archive.debian.org/debian/"
             if ansible_facts.distribution == "Debian"
            and ansible_facts.distribution_major_version is version("11", "<=")
            else "https://mirror.fsmg.org.nz/debian/" }}
        ubuntu_mirror_url: "https://mirror.fsmg.org.nz/ubuntu/"

        apt_conf_files:
          - name: 90phased-updates
            config: |
              APT::Get::Always-Include-Phased-Updates "1";

        apt_repos:
          - name: tailscale
            types: deb
            url: https://pkgs.tailscale.com/stable/{{ ansible_facts.distribution | lower }}
            suites: "{{ ansible_facts.distribution_release }}"
            components:
              - main
            gpg_key: "https://pkgs.tailscale.com/stable/{{ ansible_facts.distribution | lower }}/{{ ansible_facts.distribution_release }}.asc"

  environment:
    ANSIBLE_UNSAFE_WRITES: "true"
