---
- name: Add apt repository {{ item.name }}
  ansible.builtin.deb822_repository:
    name: "{{ item.name }}"
    types: "{{ item.types }}"
    uris: "{{ item.url }}"
    suites: "{{ item.suites }}"
    components: "{{ item.components }}"
    architectures: "{{ item.architectures | default(omit) }}"
    signed_by: "{{ item.gpg_key | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  register: _apt_repo

- name: Refresh apt cache when apt repository changes
  ansible.builtin.apt:
    update_cache: true
  when: _apt_repo is changed
