---
- name: Add public gpg signing key for {{ item.name }} apt repo
  ansible.builtin.apt_key:
    url: "{{ item.key.url }}"
    id: "{{ item.key.id | default(omit) }}"
    keyring: "{{ item.key.keyring | default(omit) }}"
    state: present

- name: Add sources.list file for {{ item.name }} apt repo
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.name }}"
    update_cache: yes
    state: present
