---

- name: Install https support for apt
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
    state: present
  when: not (ansible_distribution == "Debian" and ansible_distribution_version is version('10', '>='))

- name: Install gnupg on newer ubuntu/debian
  ansible.builtin.apt:
    pkg:
      - gnupg
    state: present
  when: >
    (ansible_distribution == "Debian" and ansible_distribution_version is version('9', '>=')) or
    (ansible_distribution == "Ubuntu" and ansible_distribution_version is version('18.04', '>='))

- name: Install gnupg2 on older ubuntu/debian
  ansible.builtin.apt:
    pkg:
      - gnupg2
    state: present
  when: >
    (ansible_distribution == "Debian" and ansible_distribution_version is version('9', '<')) or
    (ansible_distribution == "Ubuntu" and ansible_distribution_version is version('18.04', '<'))

- name: "Create apt keyrings directory"
  ansible.builtin.file:
    path: "/etc/apt/keyrings/"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Configure apt mirror
  ansible.builtin.template:
    src: "templates/sources.list.{{ ansible_lsb.id | lower }}"
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  when: ansible_os_family == "Debian"
  register: apt_mirror

- name: Refresh apt cache when mirror changes  # noqa no-handler
  ansible.builtin.apt:
    update_cache: yes
  when: apt_mirror.changed

- name: Install needrestart
  ansible.builtin.apt:
    pkg: needrestart
    install_recommends: no
    state: present

- name: Install lsb-release
  ansible.builtin.apt:
    pkg: lsb-release
    state: present

- name: Install intel microcode on physical hosts with an Intel CPU
  ansible.builtin.apt:
    pkg: "intel-microcode"
  when:
    - "ansible_virtualization_role == 'host'"
    - "ansible_processor | lower is search('intel')"

- name: Install amd64 microcode on physical hosts with an AMD CPU
  ansible.builtin.apt:
    pkg: "amd64-microcode"
  when:
    - "ansible_virtualization_role == 'host'"
    - "ansible_processor | lower is search('amd')"

- name: Install NIC specific packages when required
  ansible.builtin.apt:
    pkg: "{{ item.package }}"
    install_recommends: no
  when:
    - "item.module in loaded_nic_kmods | json_query('[*].module')"
    - "ansible_distribution | lower in item.distributions"
  loop: "{{ nic_packages }}"
  loop_control:
    label: "{{ item.module }}"

- name: Merge all useful_repos variables
  merge_vars:
    suffix_to_merge: useful_repos__merge
    merged_var_name: useful_repos
    expected_type: list
  when: not useful_repos or useful_repos | length == 0

- name: Add useful apt repos
  ansible.builtin.include_tasks:
    file: add-repo.yml
  loop: "{{ useful_repos }}"
  loop_control:
    label: "{{ item.name }}"

- name: Install useful packages
  ansible.builtin.apt:
    pkg: "{{ useful_packages }}"
    state: present

- name: Merge all packages_install variables
  merge_vars:
    suffix_to_merge: packages_install__merge
    merged_var_name: packages_install
    expected_type: list
  when: not packages_install or packages_install | length == 0

- name: Merge all packages_upgrade variables
  merge_vars:
    suffix_to_merge: packages_upgrade__merge
    merged_var_name: packages_upgrade
    expected_type: list
  when: not packages_upgrade or packages_upgrade | length == 0

- name: Merge all packages_remove variables
  merge_vars:
    suffix_to_merge: packages_remove__merge
    merged_var_name: packages_remove
    expected_type: list
  when: not packages_remove or packages_remove | length == 0

- name: Merge all packages_purge variables
  merge_vars:
    suffix_to_merge: packages_purge__merge
    merged_var_name: packages_purge
    expected_type: list
  when: not packages_purge or packages_purge | length == 0

- name: Install packages
  ansible.builtin.apt:
    pkg: "{{ packages_install }}"
    state: present

- name: Upgrade packages  # noqa package-latest
  ansible.builtin.apt:
    pkg: "{{ packages_upgrade }}"
    state: latest

- name: Remove packages
  ansible.builtin.apt:
    pkg: "{{ packages_remove }}"
    state: absent

- name: Purge packages
  ansible.builtin.apt:
    pkg: "{{ packages_purge }}"
    purge: yes
    state: absent
