---
- name: "Create apt keyrings directory"
  ansible.builtin.file:
    path: "/etc/apt/keyrings/"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: "Configure apt.conf.d files"
  ansible.builtin.template:
    src: "apt/apt.conf.d"
    dest: "/etc/apt/apt.conf.d/{{ item.name }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  loop: "{{ apt_conf_files }}"
  loop_control:
    label: "{{ item.name }}"

- name: "Configure apt preferences.d files"
  ansible.builtin.template:
    src: "apt/preferences.d"
    dest: "/etc/apt/preferences.d/{{ item.name }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  loop: "{{ apt_preference_files }}"
  loop_control:
    label: "{{ item.name }}"

- name: Install https support for apt
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
    state: present
  when: >
    not (ansible_distribution == "Debian" and ansible_distribution_version is version('10', '>='))

- name: Install gnupg on newer ubuntu/debian
  ansible.builtin.apt:
    pkg:
      - gnupg
    state: present
  when: >
    (ansible_distribution == "Debian" and ansible_distribution_version is version('9', '>=')) or
    (ansible_distribution == "Ubuntu" and ansible_distribution_version is version('18.04', '>='))

- name: Install gnupg2 on older ubuntu/debian
  ansible.builtin.apt:
    pkg:
      - gnupg2
    state: present
  when: >
    (ansible_distribution == "Debian" and ansible_distribution_version is version('9', '<')) or
    (ansible_distribution == "Ubuntu" and ansible_distribution_version is version('18.04', '<'))

- name: Configure apt mirror
  ansible.builtin.template:
    src: "apt/sources.list.{{ ansible_lsb.id | lower }}"
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  when:
    - ansible_os_family == "Debian"
    - not (ansible_distribution == "Ubuntu" and ansible_architecture not in ["x86_64", "i386"])
  register: apt_mirror

- name: Configure ubuntu ports apt mirror
  ansible.builtin.template:
    src: "apt/sources.list.{{ ansible_lsb.id | lower }}-ports"
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  when: ansible_distribution == "Ubuntu" and ansible_architecture not in ["x86_64", "i386"]
  register: apt_ubuntu_ports_mirror

- name: Refresh apt cache when mirror changes  # noqa no-handler
  ansible.builtin.apt:
    update_cache: true
  when: apt_mirror.changed or apt_ubuntu_ports_mirror.changed

- name: Install needrestart
  ansible.builtin.apt:
    pkg: needrestart
    install_recommends: false
    state: present

- name: Install lsb-release
  ansible.builtin.apt:
    pkg: lsb-release
    state: present

- name: Add additional apt repos
  ansible.builtin.include_tasks:
    file: add-repo.yml
  loop: "{{ apt_repos }}"
  loop_control:
    label: "{{ item.name }}"

- name: Install packages
  ansible.builtin.apt:
    pkg: "{{ packages_install }}"
    state: present

- name: Upgrade packages  # noqa package-latest
  ansible.builtin.apt:
    pkg: "{{ packages_upgrade }}"
    state: latest

- name: Remove packages
  ansible.builtin.apt:
    pkg: "{{ packages_remove }}"
    state: absent

- name: Purge packages
  ansible.builtin.apt:
    pkg: "{{ packages_purge }}"
    purge: true
    state: absent
