---
- name: "Create apt keyrings directory"
  ansible.builtin.file:
    path: "/etc/apt/keyrings/"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: "Configure apt.conf.d files"
  ansible.builtin.template:
    src: "apt/apt.conf.d"
    dest: "/etc/apt/apt.conf.d/{{ item.name }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  loop: "{{ apt_conf_files }}"
  loop_control:
    label: "{{ item.name }}"

- name: "Configure apt preferences.d files"
  ansible.builtin.template:
    src: "apt/preferences.d"
    dest: "/etc/apt/preferences.d/{{ item.name }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  loop: "{{ apt_preference_files }}"
  loop_control:
    label: "{{ item.name }}"

- name: Install https support for apt on older debian
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
    state: present
  when:
    - ansible_facts.distribution == "Debian"
    - ansible_facts.distribution_major_version | int > 0
    - ansible_facts.distribution_major_version is version("9", "<=")

- name: Install gnupg2 on older ubuntu/debian
  ansible.builtin.apt:
    pkg:
      - gnupg2
    state: present
  when:
    - ansible_facts.distribution_major_version | int > 0
    - (
      ansible_facts.distribution == "Debian"
      and ansible_facts.distribution_major_version is version("8", "<=")
      ) or (
      ansible_facts.distribution == "Ubuntu"
      and ansible_facts.distribution_version is version("17.10", "<=")
      )
  register: _gnupg2_install

- name: Install gnupg on newer ubuntu/debian
  ansible.builtin.apt:
    pkg:
      - gnupg
    state: present
  when:
    - _gnupg2_install is skipped

- name: Set apt deb822 fact
  ansible.builtin.set_fact:
    apt_deb822_sources: >-
      {{
        false
        if ansible_facts.distribution_major_version | int > 0
        and (
          (
            ansible_facts.distribution == "Debian"
            and ansible_facts.distribution_major_version is version("12", "<=")
          ) or (
            ansible_facts.distribution == "Ubuntu"
            and ansible_facts.distribution_version is version("23.10", "<=")
          )
        )
        else
        true
      }}

- name: Configure apt mirror
  ansible.builtin.template:
    src: "{{ _sources_template }}"
    dest: "{{ _sources_destination }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  when: ansible_facts.os_family == "Debian"
  vars:
    _sources_template: >-
      {{
        "apt/sources.list." + ansible_facts.lsb.id | lower
        if not apt_deb822_sources
        else
        "apt/" + ansible_facts.lsb.id | lower + ".sources"
      }}
    _sources_destination: >-
      {{
        "/etc/apt/sources.list"
        if not apt_deb822_sources
        else
        "/etc/apt/sources.list.d/" + ansible_facts.lsb.id | lower + ".sources"
      }}
  register: apt_mirror

- name: Refresh apt cache when mirror changes  # noqa no-handler
  ansible.builtin.apt:
    update_cache: true
  when: apt_mirror is changed

- name: Install dependencies
  ansible.builtin.apt:
    pkg:
      - lsb-release
      - python3-debian
    state: present

- name: Add additional apt repos
  ansible.builtin.include_tasks:
    file: add-repo.yml
  loop: "{{ apt_repos }}"
  loop_control:
    label: "{{ item.name }}"

- name: Install packages
  ansible.builtin.apt:
    pkg: "{{ packages_install }}"
    state: present

- name: Upgrade packages  # noqa package-latest
  ansible.builtin.apt:
    pkg: "{{ packages_upgrade }}"
    state: latest

- name: Remove packages
  ansible.builtin.apt:
    pkg: "{{ packages_remove }}"
    state: absent

- name: Purge packages
  ansible.builtin.apt:
    pkg: "{{ packages_purge }}"
    purge: true
    state: absent

- name: "Enable apt autoremove systemd timer"
  when: apt_autoremove_time != "never"
  block:
    - name: Add apt autoremove service
      ansible.builtin.template:
        src: "apt/apt-autoremove.service"
        dest: "/etc/systemd/system/apt-autoremove.service"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      register: _service_file

    - name: Add apt autoremove systemd timer
      ansible.builtin.template:
        src: "apt/apt-autoremove.timer"
        dest: "/etc/systemd/system/apt-autoremove.timer"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      register: _timer_file

    - name: Start and enable apt autoremove systemd timer
      ansible.builtin.systemd:
        name: apt-autoremove.timer
        daemon_reload: >-
          {{ true if _service_file is changed or _timer_file is changed else false }}
        state: started
        enabled: true

- name: "Disable apt autoremove systemd timer"
  when: apt_autoremove_time == "never"
  block:
    - name: Remove apt autoremove service and timer
      ansible.builtin.file:
        path: "/etc/systemd/system/{{ item }}"
        state: "absent"
      loop:
        - "apt-autoremove.service"
        - "apt-autoremove.timer"
      register: _remove_files

    - name: Disable apt autoremove systemd timer
      ansible.builtin.command:
        cmd: systemctl disable apt-autoremove.timer
      register: _systemctl_disable
      changed_when: "'removed' in _systemctl_disable.stderr | lower"
      when: _remove_files is changed

- name: "Enable apt clean systemd timer"
  when: apt_clean_time != "never"
  block:
    - name: Add apt clean service
      ansible.builtin.template:
        src: "apt/apt-clean.service"
        dest: "/etc/systemd/system/apt-clean.service"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      register: _service_file

    - name: Add apt clean systemd timer
      ansible.builtin.template:
        src: "apt/apt-clean.timer"
        dest: "/etc/systemd/system/apt-clean.timer"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      register: _timer_file

    - name: Start and enable apt clean systemd timer
      ansible.builtin.systemd:
        name: apt-clean.timer
        daemon_reload: >-
          {{ true if _service_file is changed or _timer_file is changed else false }}
        state: started
        enabled: true

- name: "Disable apt clean systemd timer"
  when: apt_clean_time == "never"
  block:
    - name: Remove apt clean service and timer
      ansible.builtin.file:
        path: "/etc/systemd/system/{{ item }}"
        state: "absent"
      loop:
        - "apt-clean.service"
        - "apt-clean.timer"
      register: _remove_files

    - name: Disable apt clean systemd timer
      ansible.builtin.command:
        cmd: systemctl disable apt-clean.timer
      register: _systemctl_disable
      changed_when: "'removed' in _systemctl_disable.stderr | lower"
      when: _remove_files is changed
